### ISSUE TITLE
CLI interface, packaging

### ISSUE THREAD

**Issue by bertsky** [MehmedGIT/OtoN_Converter#2]
Could you please encapsulate this as a setuptools package?

Also, IMO it's not useful to provide this as a file-based tool. After all, this is just about strings. Both the API and CLI should allow working without files. (For the CLI then, that would be stdin and stdout I guess.)

**Comment by MehmedGIT** [comment]
> Could you please encapsulate this as a setuptools package?

I am currently working on that.

> Also, IMO it's not useful to provide this as a file-based tool. After all, this is just about strings. Both the API and CLI should allow working without files. (For the CLI then, that would be stdin and stdout I guess.)

The file-based solution works best for the Operandi project and I think it is more convenient for general users. STDIN and STDOUT are file descriptors. Why do you think a file-based solution is not good? In the end, you still need to pass Nextflow script files as input to the Nextflow engine.
