### ISSUE TITLE
`,` is not an allowed character

### ISSUE THREAD

**Issue by mweidling** [MehmedGIT/OtoN_Converter#9]
For evaluating my OCR results I use the following minimal workflow:

```bash
ocrd process \
    "tesserocr-recognize -I OCR-D-IMG -O OCR-D-OCR -P segmentation_level region -P textequiv_level word -P find_tables true -P model Fraktur_GT4HistOCR" \
    "dinglehopper -I OCR-D-GT-SEG-BLOCK,OCR-D-OCR -O OCR-D-EVAL-SEG-BLOCK" \
```

This yields:

```bash
Convert OCR-D workflows to NextFlow …
Converting from: minimal.txt
Converting to: minimal.txt.nf
Syntax error!
Invalid line number: 2!
Info: TOKEN_SYMBOL_ERROR_RULE_03: Invalid token: OCR-D-GT-SEG-BLOCK,OCR-D-OCR.
Hint: Tokens cannot contain character: ,.
```

Since the syntax of the workflow is correct according to https://ocr-d.de/en/workflows#step-18-ocr-evaluation, `,` has to be allowed under certain circumstances.

**Comment by MehmedGIT** [comment]
@mweidling, thanks for reporting that. I will try to push a patch that fixes this issue today.

**Comment by mweidling** [comment]
> In the minimal workflow example, you provided, the last line must not contain \. This is something that the validator complained about as well. It is the expected behavior.

My bad, that's a copy & paste error.

**Comment by MehmedGIT** [comment]
This should be fixed now. 

Still worth mentioning that the input/output match validation is not performed now. The match validation for that will be implemented after some refactoring of the code. It's now the user's responsibility to provide the correct -I/-O values in the ocr-d workflow.txt file.
